### ISSUE TITLE
How could i use code highlighter in editorjs-parser?

### ISSUE THREAD

**Issue by coderkhalide** [MichaelMikeJones/editorjs-parser#3]
I am trying to use react-highlight.js to highlight my code. 
but I am getting _[object Object]_ on the output.

```javascript
const customParsers = {
    code: function(data){
        return (<Highlight language="javascript">
             {data.code}
         </Highlight>)
    }
}

const parser = new edjsParser(config, customParsers);
```

**Comment by MichaelMikeJones** [comment]
Your code looks fine. I tested my code and it apparently is okay (I only tested it in backend). But I don't know react and this strange syntax of react.
What i propose is, you print `data` and `data.code` to console before the return statement and see if it looks okay. (I guess `data` only contains `code` variable)

**Comment by coderkhalide** [comment]
> Your code looks fine. I tested my code and it apparently is okay (I only tested it in backend). But I don't know react and this strange syntax of react.
> What i propose is, you print `data` and `data.code` to console before the return statement and see if it looks okay. (I guess `data` only contains `code` variable)
